// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Password  string `json:"password"`
}

type Search struct {
	Users []*User `json:"users"`
}

type UserCredentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
