// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Block struct {
	UserID  string `json:"userId"`
	BlockID string `json:"blockId"`
}

type CreateJob struct {
	Title          string `json:"title"`
	CompanyName    string `json:"companyName"`
	Workplace      string `json:"workplace"`
	City           string `json:"city"`
	Country        string `json:"country"`
	EmploymentType string `json:"employmentType"`
	Description    string `json:"description"`
}

type Hashtag struct {
	ID      string `json:"id"`
	Hashtag string `json:"hashtag"`
}

type InputPost struct {
	SenderID string `json:"senderId"`
	Text     string `json:"text"`
	PhotoURL string `json:"photoUrl"`
	VideoURL string `json:"videoUrl"`
}

type Job struct {
	ID             string    `json:"id"`
	Title          string    `json:"title"`
	CompanyName    string    `json:"companyName"`
	Workplace      string    `json:"workplace"`
	City           string    `json:"city"`
	Country        string    `json:"country"`
	EmploymentType string    `json:"employmentType"`
	Description    string    `json:"description"`
	CreatedAt      time.Time `json:"createdAt"`
}

type NewExperience struct {
	UserID         string `json:"UserID"`
	Title          string `json:"Title"`
	EmploymentType string `json:"EmploymentType"`
	CompanyName    string `json:"CompanyName"`
	Location       string `json:"Location"`
	Active         bool   `json:"Active"`
	StartYear      string `json:"StartYear"`
	EndYear        string `json:"EndYear"`
	Industry       string `json:"Industry"`
	Description    string `json:"Description"`
}

type NewUser struct {
	Email     string `json:"email"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Password  string `json:"password"`
}

type Search struct {
	Users []*User `json:"Users"`
	Posts []*Post `json:"Posts"`
}

type UserCredentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewEducation struct {
	UserID       string  `json:"UserID"`
	School       string  `json:"School"`
	Degree       string  `json:"Degree"`
	FieldOfStudy string  `json:"FieldOfStudy"`
	StartDate    string  `json:"StartDate"`
	EndDate      string  `json:"EndDate"`
	Grade        float64 `json:"Grade"`
	Activities   string  `json:"Activities"`
	Description  string  `json:"Description"`
}
